[tool.black]
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.git
    | \.tox
    | \.eggs
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3

known_first_party = ["testinfra"]
