name: tox

on:
  create:  # is used for publishing to TestPyPI
    tags:  # any tag regardless of its name, no branches
      - "**"
  push:  # only publishes pushes to the main branch to TestPyPI
    branches:  # any integration branch but not tag
      - "main"
  pull_request:
  release:
    types:
      - published  # It seems that you can publish directly without creating
  schedule:
    - cron: 1 0 * * *  # Run daily at 0:01 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  pre:
    name: pre
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.generate_matrix.outputs.matrix }}
    steps:
      - name: Determine matrix
        id: generate_matrix
        uses: coactions/matrix@main
        with:
          min_python: "3.8"
          max_python: "3.10"
          other_names: |
            lint
            docs
            packaging
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs: pre
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.pre.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Even our lint and other envs need access to tox
      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          docker version
          docker info
          python -m pip install -U pip
          pip install tox
      - name: Run tox -e ${{ matrix.passed_name }}
        run: |
          echo "${{ matrix.PREFIX }} tox -e ${{ matrix.passed_name }}"
          ${{ matrix.PREFIX }} tox -e ${{ matrix.passed_name }}

  check: # This job does nothing and is only used for the branch protection
    if: always()
    permissions:
      pull-requests: write # allow codenotify to comment on pull-request
    needs:
      - build
    runs-on: ubuntu-22.04

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
